#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
    ln -s /usr/lib/rustdesk/Yangdiskservice /usr/bin/Yangdiskservice
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/Yangdiskservice.service ]; then
			rm /etc/systemd/system/Yangdiskservice.service /usr/lib/systemd/system/Yangdiskservice.service /usr/lib/systemd/user/Yangdiskservice.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk/files/systemd/Yangdiskservice.service /usr/lib/systemd/system/Yangdiskservice.service
		# try fix error in Ubuntu 18.04
		# Failed to reload Yangdiskservice.service: Unit Yangdiskservice.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/Yangdiskservice.service:10: Executable path is not absolute: pkill -f "rustdesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/Yangdiskservice.service
		fi
		systemctl daemon-reload
		systemctl enable Yangdiskservice
		systemctl start Yangdiskservice
	fi
fi
