#!/bin/bash

set -e

case $1 in
    remove|upgrade)
		INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
        rm /usr/bin/lidesk
		
		if [ "systemd" == "${INITSYS}" ]; then

			systemctl stop lidesk || true
			systemctl disable lidesk || true
			rm /etc/systemd/system/lidesk.service /usr/lib/systemd/system/lidesk.service || true
			
			# workaround temp dev build between 1.1.9 and 1.2.0
			serverUser=$(ps -ef | grep -E 'rustdesk +--server' | grep -v 'sudo ' | awk '{print $1}' | head -1)
			if [ "$serverUser" != "" ] && [ "$serverUser" != "root" ]
			then
				systemctl --machine=${serverUser}@.host --user stop lidesk >/dev/null 2>&1 || true
			fi
			rm /usr/lib/systemd/user/lidesk.service >/dev/null 2>&1 || true
		fi
        ;;
esac

exit 0
